/* DO NOT EDIT THIS FILE - it is machine generated */
#include<string.h>
#include <jni.h>
/* Header for class com_android_framework_ndk_NdkTest */

#ifndef _Included_com_android_framework_ndk_NdkTest
#define _Included_com_android_framework_ndk_NdkTest
#ifdef __cplusplus
extern "C" {
#endif

extern const char key[];
extern int len;



/*
 * Class:     com_android_framework_ndk_NdkTest
 * Method:    getStringInNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_framework_ndk_NdkTest_getStringInNDK
        (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_android_framework_ndk_NdkTest_converseInSo
        (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_android_framework_ndk_NdkTest_encryptString
        (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_android_framework_ndk_NdkTest_decryptString
        (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
